In [1]:
import numpy as np
import pandas as pd
from math import sqrt
import scipy
from scipy import linalg

def SVD(A):
    print(A)
    AT = A.transpose()
    AdotAT = A.dot(AT)
    ATdotA = AT.dot(A)            
    S, V = linalg.eig(ATdotA)
    
    V_tr = V.transpose()
   
    S = np.diag(np.sqrt(S))
    inv_S = np.linalg.inv(S)    

    U = A.dot(V).dot(inv_S)
    USV_t = U.dot(S.dot(V_tr))
    print("THE S :\n")
    print(S)
    print("THE V :\n")
    print(V)
    print("THE U :\n")
    print(U)
    print("THE USV^t :\n")
    print(USV_t)
    return 0

A = np.array([[0, 1, 1], [sqrt(2), 2, 0], [0, 1, 1]])
#A = np.array([[0, sqrt(2), 0], [1, 2, 1], [1, 0, 1]])
SVD(A)

[[0.         1.         1.        ]
 [1.41421356 2.         0.        ]
 [0.         1.         1.        ]]
THE S :

[[2.82842712+0.00000000e+00j 0.        +0.00000000e+00j
  0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +2.77167193e-09j
  0.        +0.00000000e+00j]
 [0.        +0.00000000e+00j 0.        +0.00000000e+00j
  1.41421356+0.00000000e+00j]]
THE V :

[[-4.08248290e-01  7.07106781e-01 -5.77350269e-01]
 [-8.66025404e-01 -5.00000000e-01 -7.84321844e-17]
 [-2.88675135e-01  5.00000000e-01  8.16496581e-01]]
THE U :

[[-0.40824829+0.00000000e+00j  0.        +4.00560763e-08j
   0.57735027+0.00000000e+00j]
 [-0.81649658+0.00000000e+00j  0.        -8.01121526e-08j
  -0.57735027+0.00000000e+00j]
 [-0.40824829+0.00000000e+00j  0.        +4.00560763e-08j
   0.57735027+0.00000000e+00j]]
THE USV^t :

[[-1.08373789e-17+0.j  1.00000000e+00+0.j  1.00000000e+00+0.j]
 [ 1.41421356e+00+0.j  2.00000000e+00+0.j -5.49219252e-16+0.j]
 [-1.08373789e-17+0.j  1.00000000e+00+0.j  1

0